### ISSUE TITLE
Italics text not displayed accordingly

### ISSUE THREAD

**Issue by medwatt** [woutersj/tm-pygments#2]
For some reason, italics text inside the pygments environment are not displayed the same way italics text outside it are. It seems that italics text is simply a slanted version of the regular text. Any idea how to fix this?

![](https://i.imgur.com/bEafORa.png)

**Comment by woutersj** [comment]
The plugin itself doesn't do the typesetting of the text. It simply passes to TeXmacs whether or not text should be italic, in which colour, etc. All of the code is put inside a `verbatim-code` tag, so the text in question should be formatted in a mono-spaced italic or oblique font corresponding to the document font. If the font is not displayed as you expect it, you can file a bug at [TeXmacs' bug tracker on savannah](https://savannah.gnu.org/bugs/?group=texmacs)
