### ISSUE TITLE
pygments plugin is not found

### ISSUE THREAD

**Issue by codelover2k** [woutersj/tm-pygments#4]
I am running texmacs on macOS but suddenly, after a fresh install of texmacs tm-pygments is not found

other plugins are found. So I deleted .TaXmacs, started texmacs again, also went to:
Tools > Update > Plugins and restarted texmacs, but nothing, pygments is not found

I do not know how to debug it or how to figure out why pygments is not found

grateful for any help!

**Comment by woutersj** [comment]
Could you try to do `import pygments` from a _Python session_? Can you also please provide the outcome of `(url-resolve-in-path (python-command))` in a _Scheme session_?

**Comment by woutersj** [comment]
I've just committed an improvement to the detection of Pygments. Could you please pull the changes and see if it fixes the problem?

**Comment by codelover2k** [comment]
after installing the latest version, it is getting detected
thanks for the fix!

**Comment by woutersj** [comment]
You're welcome. Thanks for reporting.

**Comment by codelover2k** [comment]
I just noticed that it add extra identation on the left that it did not do before

**Comment by woutersj** [comment]
Could you make a screenshot and indicate the indentation?

**Comment by woutersj** [comment]
I believe I have changed the containing element from `verbatim` to `verbatim-code`, which has indentation. You can put the cursor inside the element and click the wrench icon in the toolbar to change the "Indent indentation".

**Comment by codelover2k** [comment]
this fixed the issue
<img width="554" alt="Bildschirmfoto 2022-05-03 um 14 18 36" src="https://user-images.githubusercontent.com/56235077/166451440-ffb2f718-1f0a-40c8-b548-6a5f3e77401d.png">
and then set to 0 like this:
<img width="273" alt="Bildschirmfoto 2022-05-03 um 14 18 45" src="https://user-images.githubusercontent.com/56235077/166451486-8cf28b29-2ca2-41e3-a134-2b6f4524e7bf.png">
thanks again!
