### ISSUE TITLE
pygments is not sufficient - lets replace it!

### ISSUE THREAD

**Issue by codelover2k** [woutersj/tm-pygments#7]
I noticed that pygments has some flaws.
For example it does not understand what a method is. It also does not support many languages and themes.

There is a JavaScript library called **highlightjs**:
https://highlightjs.org/static/demo/

It supports 197 languages and 248 styles and it would be great to have that power in TeXmacs!

**Comment by woutersj** [comment]
Thanks, that's an interesting suggestion. Tm-pygments was an exercise in writing plugins for myself. I don't in fact use it myself, so I'm not inclined to redo it. I'd be happy to assist you in doing so, though.

**Comment by codelover2k** [comment]
thanks!
I will try to find some time, study your solution more and try some things
I have some ideas, I guess we have to use js2py

let me know if you are on gitter or discord to discuss further details :)
